export const GET_LFP_USERS = 'GET_LFP_USERS';
export const LFP_USERS_SUCCESS = 'LFP_USERS_SUCCESS'
export const GET_LFP_USER = 'GET_LFP_USER';
export const LFP_USER_SUCCESS = 'LFP_USER_SUCCESS'
export const DELETE_LFP_USER = 'DELETE_LFP_USER';
export const LFP_USER_REMOVE_SUCCESS = 'LFP_USER_REMOVE_SUCCESS'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS' 


